Documentation of Parallel Configuration Parameters and Fixes to Defect Vertex Perfect Matching in ParallelSolver
yuewuo/fusion-blossom pull request #43
Opened 2024-06-05 21:18 UTC by YangLiuWillow

- Added python script and a markdown file on the parallel configuration using the fusion_blossom library 
- Fixed the defect vertex perfect matching "our of index range" issue in ParallelSolver by adding the 'defect_perfect_matching' method to SolverParallel struct in Rust. 
- Attempted to note down the function input and output for the fusion_blossom library.

2024-06-05 21:21 UTC, YangLiuWillow commented
Fixes #34

2024-06-14 14:51 UTC, yuewuo requested changes

2024-06-14 14:51 UTC, yuewuo commented on src/util.rs
> +            println!("here the filename is {}", filename);
Consider removing unnecessary prints

2024-06-14 14:51 UTC, yuewuo commented on tutorial/src/demo/example-parallel-yl.md
> +In paper [1], Fusion Blossom solves the MWPM problem with a Divide and Conquer approach. Fusion Blossom *divides* the decoding problem into two sub-problems that can be solved, or "conquered," indepe
```suggestion
In paper [1], Fusion Blossom solves the MWPM problem with a Divide and Conquer approach. Fusion Blossom *divides* the decoding problem into two sub-problems that can be solved, or "conquered", independently and *fuses* their solutions recursively to obtain the overall solution. This recursive division/fusion is represented as a full binary tree, denoted as a *fusion tree*. 
```

2024-06-14 14:51 UTC, yuewuo commented on tutorial/src/demo/example-parallel-yl.md
> +In this chapter, you will learn how about the configuration of graph partitions and different fusion plans as explained in the paper [1]. Make sure you understand the decoding and syndrome graph befo
consider removing the `-yl` suffix

2024-06-14 14:51 UTC, yuewuo commented on tutorial/src/demo/example-parallel-yl.py
> +import fusion_blossom as fb
remove the filename to remove `-yl` suffix

2024-06-14 14:51 UTC, yuewuo commented on tutorial/src/demo/python-documentation.md
> +    * `max_half_weight`: the library scales the edge weight such that the maximum weight is 500 * 2
```suggestion
    * `max_half_weight`: the library scales the edge weight such that the maximum weight is 2 * `max_half_weight`
```

2024-06-17 17:44 UTC, YangLiuWillow reviewed
I just modified the files according to the review.

2024-06-17 17:51 UTC, yuewuo approved these changes

2024-06-17 17:51 UTC, merged